package com.pscsw.po;

import java.util.Date;

public class ClassInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.id
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.state
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.class_number
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    private String classNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.class_name
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.class_teacher
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    private String classTeacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.class_school
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    private String classSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.create_time
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.id
     *
     * @return the value of class_info.id
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.id
     *
     * @param id the value for class_info.id
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.state
     *
     * @return the value of class_info.state
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.state
     *
     * @param state the value for class_info.state
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.class_number
     *
     * @return the value of class_info.class_number
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public String getClassNumber() {
        return classNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.class_number
     *
     * @param classNumber the value for class_info.class_number
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public void setClassNumber(String classNumber) {
        this.classNumber = classNumber == null ? null : classNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.class_name
     *
     * @return the value of class_info.class_name
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.class_name
     *
     * @param className the value for class_info.class_name
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.class_teacher
     *
     * @return the value of class_info.class_teacher
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public String getClassTeacher() {
        return classTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.class_teacher
     *
     * @param classTeacher the value for class_info.class_teacher
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public void setClassTeacher(String classTeacher) {
        this.classTeacher = classTeacher == null ? null : classTeacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.class_school
     *
     * @return the value of class_info.class_school
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public String getClassSchool() {
        return classSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.class_school
     *
     * @param classSchool the value for class_info.class_school
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public void setClassSchool(String classSchool) {
        this.classSchool = classSchool == null ? null : classSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.create_time
     *
     * @return the value of class_info.create_time
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.create_time
     *
     * @param createTime the value for class_info.create_time
     *
     * @mbg.generated Mon Oct 08 09:56:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}