package com.pscsw.po;

import java.util.Date;

public class FeeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_info.id
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_info.state
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_info.fee_number
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String feeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_info.class_name
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_info.class_fee
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Float classFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_info.class_fee_record
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Float classFeeRecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_info.class_fee_detail
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String classFeeDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_info.create_time
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_info.id
     *
     * @return the value of fee_info.id
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_info.id
     *
     * @param id the value for fee_info.id
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_info.state
     *
     * @return the value of fee_info.state
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_info.state
     *
     * @param state the value for fee_info.state
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_info.fee_number
     *
     * @return the value of fee_info.fee_number
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getFeeNumber() {
        return feeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_info.fee_number
     *
     * @param feeNumber the value for fee_info.fee_number
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setFeeNumber(String feeNumber) {
        this.feeNumber = feeNumber == null ? null : feeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_info.class_name
     *
     * @return the value of fee_info.class_name
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_info.class_name
     *
     * @param className the value for fee_info.class_name
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_info.class_fee
     *
     * @return the value of fee_info.class_fee
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Float getClassFee() {
        return classFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_info.class_fee
     *
     * @param classFee the value for fee_info.class_fee
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setClassFee(Float classFee) {
        this.classFee = classFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_info.class_fee_record
     *
     * @return the value of fee_info.class_fee_record
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Float getClassFeeRecord() {
        return classFeeRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_info.class_fee_record
     *
     * @param classFeeRecord the value for fee_info.class_fee_record
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setClassFeeRecord(Float classFeeRecord) {
        this.classFeeRecord = classFeeRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_info.class_fee_detail
     *
     * @return the value of fee_info.class_fee_detail
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getClassFeeDetail() {
        return classFeeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_info.class_fee_detail
     *
     * @param classFeeDetail the value for fee_info.class_fee_detail
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setClassFeeDetail(String classFeeDetail) {
        this.classFeeDetail = classFeeDetail == null ? null : classFeeDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_info.create_time
     *
     * @return the value of fee_info.create_time
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_info.create_time
     *
     * @param createTime the value for fee_info.create_time
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}