package com.pscsw.po;

import java.util.Date;

public class FeeRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_record.id
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_record.state
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_record.account
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_record.fee_number
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String feeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_record.fee_total
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Float feeTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_record.fee_detail
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String feeDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_record.fee_time
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Date feeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_record.id
     *
     * @return the value of fee_record.id
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_record.id
     *
     * @param id the value for fee_record.id
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_record.state
     *
     * @return the value of fee_record.state
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_record.state
     *
     * @param state the value for fee_record.state
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_record.account
     *
     * @return the value of fee_record.account
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_record.account
     *
     * @param account the value for fee_record.account
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_record.fee_number
     *
     * @return the value of fee_record.fee_number
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getFeeNumber() {
        return feeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_record.fee_number
     *
     * @param feeNumber the value for fee_record.fee_number
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setFeeNumber(String feeNumber) {
        this.feeNumber = feeNumber == null ? null : feeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_record.fee_total
     *
     * @return the value of fee_record.fee_total
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Float getFeeTotal() {
        return feeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_record.fee_total
     *
     * @param feeTotal the value for fee_record.fee_total
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setFeeTotal(Float feeTotal) {
        this.feeTotal = feeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_record.fee_detail
     *
     * @return the value of fee_record.fee_detail
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getFeeDetail() {
        return feeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_record.fee_detail
     *
     * @param feeDetail the value for fee_record.fee_detail
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setFeeDetail(String feeDetail) {
        this.feeDetail = feeDetail == null ? null : feeDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_record.fee_time
     *
     * @return the value of fee_record.fee_time
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Date getFeeTime() {
        return feeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_record.fee_time
     *
     * @param feeTime the value for fee_record.fee_time
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setFeeTime(Date feeTime) {
        this.feeTime = feeTime;
    }
}