package com.pscsw.po;

import java.util.Date;

public class StudentReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.id
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.state
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.student_name
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.student_number
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    private String studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.student_class
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    private String studentClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.subject_name
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    private String subjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.subject_number
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    private String subjectNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.examination_score
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    private Integer examinationScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.examination_time
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    private Date examinationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.examination_rank
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    private Integer examinationRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.create_time
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.id
     *
     * @return the value of student_report.id
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.id
     *
     * @param id the value for student_report.id
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.state
     *
     * @return the value of student_report.state
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.state
     *
     * @param state the value for student_report.state
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.student_name
     *
     * @return the value of student_report.student_name
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.student_name
     *
     * @param studentName the value for student_report.student_name
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.student_number
     *
     * @return the value of student_report.student_number
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.student_number
     *
     * @param studentNumber the value for student_report.student_number
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber == null ? null : studentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.student_class
     *
     * @return the value of student_report.student_class
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public String getStudentClass() {
        return studentClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.student_class
     *
     * @param studentClass the value for student_report.student_class
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public void setStudentClass(String studentClass) {
        this.studentClass = studentClass == null ? null : studentClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.subject_name
     *
     * @return the value of student_report.subject_name
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.subject_name
     *
     * @param subjectName the value for student_report.subject_name
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.subject_number
     *
     * @return the value of student_report.subject_number
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public String getSubjectNumber() {
        return subjectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.subject_number
     *
     * @param subjectNumber the value for student_report.subject_number
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public void setSubjectNumber(String subjectNumber) {
        this.subjectNumber = subjectNumber == null ? null : subjectNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.examination_score
     *
     * @return the value of student_report.examination_score
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public Integer getExaminationScore() {
        return examinationScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.examination_score
     *
     * @param examinationScore the value for student_report.examination_score
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public void setExaminationScore(Integer examinationScore) {
        this.examinationScore = examinationScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.examination_time
     *
     * @return the value of student_report.examination_time
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public Date getExaminationTime() {
        return examinationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.examination_time
     *
     * @param examinationTime the value for student_report.examination_time
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public void setExaminationTime(Date examinationTime) {
        this.examinationTime = examinationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.examination_rank
     *
     * @return the value of student_report.examination_rank
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public Integer getExaminationRank() {
        return examinationRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.examination_rank
     *
     * @param examinationRank the value for student_report.examination_rank
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public void setExaminationRank(Integer examinationRank) {
        this.examinationRank = examinationRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.create_time
     *
     * @return the value of student_report.create_time
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_report.create_time
     *
     * @param createTime the value for student_report.create_time
     *
     * @mbg.generated Mon Oct 08 16:08:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}