package com.pscsw.po;

import java.util.Date;

public class StudentInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.id
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.state
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.account
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_name
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_number
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_parent
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String studentParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_class
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String studentClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_department
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private String studentDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.create_time
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.id
     *
     * @return the value of student_info.id
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.id
     *
     * @param id the value for student_info.id
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.state
     *
     * @return the value of student_info.state
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.state
     *
     * @param state the value for student_info.state
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.account
     *
     * @return the value of student_info.account
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.account
     *
     * @param account the value for student_info.account
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_name
     *
     * @return the value of student_info.student_name
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_name
     *
     * @param studentName the value for student_info.student_name
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_number
     *
     * @return the value of student_info.student_number
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_number
     *
     * @param studentNumber the value for student_info.student_number
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber == null ? null : studentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_parent
     *
     * @return the value of student_info.student_parent
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getStudentParent() {
        return studentParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_parent
     *
     * @param studentParent the value for student_info.student_parent
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setStudentParent(String studentParent) {
        this.studentParent = studentParent == null ? null : studentParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_class
     *
     * @return the value of student_info.student_class
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getStudentClass() {
        return studentClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_class
     *
     * @param studentClass the value for student_info.student_class
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setStudentClass(String studentClass) {
        this.studentClass = studentClass == null ? null : studentClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_department
     *
     * @return the value of student_info.student_department
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public String getStudentDepartment() {
        return studentDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_department
     *
     * @param studentDepartment the value for student_info.student_department
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setStudentDepartment(String studentDepartment) {
        this.studentDepartment = studentDepartment == null ? null : studentDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.create_time
     *
     * @return the value of student_info.create_time
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.create_time
     *
     * @param createTime the value for student_info.create_time
     *
     * @mbg.generated Sun Oct 07 22:22:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}