package com.pscsw.dao;

import com.pscsw.po.ClassInfo;
import com.pscsw.po.SubjectInfo;

public interface ClassInfoMapper {
	ClassInfo[] selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table class_info
	 *
	 * @mbg.generated Mon Oct 08 09:56:59 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table class_info
	 *
	 * @mbg.generated Mon Oct 08 09:56:59 CST 2018
	 */
	int insert(ClassInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table class_info
	 *
	 * @mbg.generated Mon Oct 08 09:56:59 CST 2018
	 */
	int insertSelective(ClassInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table class_info
	 *
	 * @mbg.generated Mon Oct 08 09:56:59 CST 2018
	 */
	ClassInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table class_info
	 *
	 * @mbg.generated Mon Oct 08 09:56:59 CST 2018
	 */
	int updateByPrimaryKeySelective(ClassInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table class_info
	 *
	 * @mbg.generated Mon Oct 08 09:56:59 CST 2018
	 */
	int updateByPrimaryKey(ClassInfo record);
}