package com.pscsw.dao;

import com.pscsw.po.FeeInfo;
import com.pscsw.po.FeeRecord;

public interface FeeRecordMapper {
	FeeRecord[] selectByFeeNumber(String fee_number);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fee_record
	 *
	 * @mbg.generated Sun Oct 07 22:22:17 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fee_record
	 *
	 * @mbg.generated Sun Oct 07 22:22:17 CST 2018
	 */
	int insert(FeeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fee_record
	 *
	 * @mbg.generated Sun Oct 07 22:22:17 CST 2018
	 */
	int insertSelective(FeeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fee_record
	 *
	 * @mbg.generated Sun Oct 07 22:22:17 CST 2018
	 */
	FeeRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fee_record
	 *
	 * @mbg.generated Sun Oct 07 22:22:17 CST 2018
	 */
	int updateByPrimaryKeySelective(FeeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table fee_record
	 *
	 * @mbg.generated Sun Oct 07 22:22:17 CST 2018
	 */
	int updateByPrimaryKey(FeeRecord record);
}