package com.pscsw.dao;

import com.pscsw.po.SubjectInfo;
import com.pscsw.po.User;

public interface SubjectInfoMapper {
	SubjectInfo[] selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table subject_info
	 *
	 * @mbg.generated Sun Oct 07 18:16:23 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table subject_info
	 *
	 * @mbg.generated Sun Oct 07 18:16:23 CST 2018
	 */
	int insert(SubjectInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table subject_info
	 *
	 * @mbg.generated Sun Oct 07 18:16:23 CST 2018
	 */
	int insertSelective(SubjectInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table subject_info
	 *
	 * @mbg.generated Sun Oct 07 18:16:23 CST 2018
	 */
	SubjectInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table subject_info
	 *
	 * @mbg.generated Sun Oct 07 18:16:23 CST 2018
	 */
	int updateByPrimaryKeySelective(SubjectInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table subject_info
	 *
	 * @mbg.generated Sun Oct 07 18:16:23 CST 2018
	 */
	int updateByPrimaryKey(SubjectInfo record);
}