package example.com.primaryschoolconnectedsystemapp.account;

import java.util.Date;

import okhttp3.FormBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.state
     *
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account
     *
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    private String name;
    public String userName;
    public String userNick;
    public String userXuehao;
    public String userClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.certificate_id
     *
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    private String certificateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_time
     *
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.state
     *
     * @return the value of user.state
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.state
     *
     * @param state the value for user.state
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account
     *
     * @return the value of user.account
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account
     *
     * @param account the value for user.account
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.certificate_id
     *
     * @return the value of user.certificate_id
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public String getCertificateId() {
        return certificateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.certificate_id
     *
     * @param certificateId the value for user.certificate_id
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public void setCertificateId(String certificateId) {
        this.certificateId = certificateId == null ? null : certificateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_time
     *
     * @return the value of user.login_time
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_time
     *
     * @param loginTime the value for user.login_time
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     * @mbg.generated Thu Oct 04 09:50:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public boolean register() {
        OkHttpClient okHttpClient = new OkHttpClient();
        //Form表单格式的参数传递
        FormBody formBody = new FormBody
                .Builder()
                .add("cmd", "register")//设置参数名称和参数值
                .add("account", account)//设置参数名称和参数值
                .add("password", password)//设置参数名称和参数值
                .add("name", name)//设置参数名称和参数值
                .build();
        Request request = new Request
                .Builder().
                post(formBody)//Post请求的参数传递，此处是和Get请求相比，多出的一句代码</font>
                .url(HttpPost.POST_URL)
                .build();
        try {
            Response response = okHttpClient.newCall(request).execute();
            String result = response.body().string();
            if (helper.getStatusCode(result, "status") == HttpPost.STATUS_OK) {
                return true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    public boolean login() {
        OkHttpClient okHttpClient = new OkHttpClient();
        //Form表单格式的参数传递
        FormBody formBody = new FormBody
                .Builder()
                .add("cmd", "login")//设置参数名称和参数值
                .add("account", account)//设置参数名称和参数值
                .add("password", password)//设置参数名称和参数值
                .build();
        Request request = new Request
                .Builder().
                post(formBody)//Post请求的参数传递，此处是和Get请求相比，多出的一句代码</font>
                .url(HttpPost.POST_URL)
                .build();
        try {
            Response response = okHttpClient.newCall(request).execute();
            String result = response.body().string();
            if (helper.getStatusCode(result, "status") == HttpPost.STATUS_OK) {
                helper.user.name = helper.getResValue(result, "name");
                helper.user.userName = helper.getResValue(result, "userName");
                helper.user.userNick = helper.getResValue(result, "userNick");
                helper.user.userXuehao = helper.getResValue(result, "userXuehao");
                helper.user.userClass = helper.getResValue(result, "userClass");
                return true;
            }
        } catch (Exception e) {
        }
        return false;
    }

    public boolean modifyInfo(String userName, String userNick, String userXuehao, String userClass) {
        OkHttpClient okHttpClient = new OkHttpClient();
        //Form表单格式的参数传递
        FormBody formBody = new FormBody
                .Builder()
                .add("cmd", "modifyInfo")//设置参数名称和参数值
                .add("account", account)//设置参数名称和参数值
                .add("password", password)//设置参数名称和参数值
                .add("userName", userName)//设置参数名称和参数值
                .add("userNick", userNick)//设置参数名称和参数值
                .add("userXuehao", userXuehao)//设置参数名称和参数值
                .add("userClass", userClass)//设置参数名称和参数值
                .build();
        Request request = new Request
                .Builder().
                post(formBody)//Post请求的参数传递，此处是和Get请求相比，多出的一句代码</font>
                .url(HttpPost.POST_URL)
                .build();
        try {
            Response response = okHttpClient.newCall(request).execute();
            String result = response.body().string();
            if (helper.getStatusCode(result, "status") == HttpPost.STATUS_OK) {
                helper.user.name = helper.getResValue(result, "name");
                helper.user.userName = helper.getResValue(result, "userName");
                helper.user.userNick = helper.getResValue(result, "userNick");
                helper.user.userXuehao = helper.getResValue(result, "userXuehao");
                helper.user.userClass = helper.getResValue(result, "userClass");
                return true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    public boolean modifyPassword(String password2) {
        OkHttpClient okHttpClient = new OkHttpClient();
        //Form表单格式的参数传递
        FormBody formBody = new FormBody
                .Builder()
                .add("cmd", "modifyPassword")//设置参数名称和参数值
                .add("account", account)//设置参数名称和参数值
                .add("password", password)//设置参数名称和参数值
                .add("password2", password2)//设置参数名称和参数值
                .build();
        Request request = new Request
                .Builder().
                post(formBody)//Post请求的参数传递，此处是和Get请求相比，多出的一句代码</font>
                .url(HttpPost.POST_URL)
                .build();
        try {
            Response response = okHttpClient.newCall(request).execute();
            String result = response.body().string();
            if (helper.getStatusCode(result, "status") == HttpPost.STATUS_OK) {
                return true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    public boolean modifyInfo() {
        OkHttpClient okHttpClient = new OkHttpClient();
        //Form表单格式的参数传递
        FormBody formBody = new FormBody
                .Builder()
                .add("cmd", "modifyInfo")//设置参数名称和参数值
                .add("account", account)//设置参数名称和参数值
                .add("password", password)//设置参数名称和参数值
                .add("name", name)//设置参数名称和参数值
                .build();
        Request request = new Request
                .Builder().
                post(formBody)//Post请求的参数传递，此处是和Get请求相比，多出的一句代码</font>
                .url(HttpPost.POST_URL)
                .build();
        try {
            Response response = okHttpClient.newCall(request).execute();
            String result = response.body().string();
            if (helper.getStatusCode(result, "status") == HttpPost.STATUS_OK) {
                helper.user.name = helper.getResValue(result, "name");
                return true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }
}